# -*- coding: utf-8 -*-
"""Ações.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/michaelstallone87/6ea3f053c53f94784c689a295dbdce84/a-es.ipynb
"""

# importar as bibliotecas necessárias
import pandas as pd
from pandas_datareader import data as web
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns


# criar um DataFrame vazio
df = pd.DataFrame()

# escolher a ação desejada
acoes = [f'MELI34.SA',f'MGLU3.SA',f'PSSA3.SA']
MELI34_acoes = 6
MGLU3_acoes = 30
PSSA3_acoes = 2

# importar dados para o DataFrame
df = web.DataReader(acoes, data_source='yahoo', start='05-01-2021')
#df = df[df['Volume'] > 0]
df = df['Close']
df['MELI34_acoes'] = df['MELI34.SA'] * MELI34_acoes
df['MGLU3_acoes'] = df['MGLU3.SA'] * MGLU3_acoes
df['PSSA3_acoes'] = df['PSSA3.SA'] * PSSA3_acoes
df['TOTAL'] = df['MELI34_acoes'] + df['MGLU3_acoes'] + df['PSSA3_acoes']

# ver as 5 primeiras entradas
dfview = df.sort_index(axis=0, ascending=False).reset_index()
dfview.to_excel('acoes.xlsx', index=False)
dfview.head()

df['TOTAL'].plot()

df[['MELI34_acoes','MGLU3_acoes','PSSA3_acoes']].describe()

df[['MELI34_acoes','MGLU3_acoes','PSSA3_acoes']].corr()

sns.boxplot(data=df['TOTAL'],orient='horizont')

sns.distplot(df['TOTAL'])

sns.boxplot(data=df[['MELI34.SA','PSSA3.SA', 'MGLU3.SA']],orient='horizont')

